version: 1
default_environment: dev
project_id: aa998ba2-db5f-489a-a8e4-24f130c7a43b
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      database: northwind
      host: localhost
      password: admin
      port: 5432
      user: admin
      default_replication_method: LOG_BASED
      stream_maps:
        public-products:
          unit_price: float(unit_price)
          __alias__: products
        public-orders:
          freight: float(freight)
          __alias__: orders

        public-categories:
          __alias__: categories
        public-customers:
          __alias__: customers
        public-employee_territories:
          __alias__: employee_territories
        public-employees:
          __alias__: employees
        public-region:
          __alias__: region
        public-shippers:
          __alias__: shippers
        public-suppliers:
          __alias__: suppliers
        public-territories:
          __alias__: territories
        public-us_states:
          __alias__: us_states
    select:
    - public-*.*


  - name: tap-csv-from-csv
    inherit_from: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files: [{entity: orders_details, path: data/order_details.csv, keys: [order_id, ##talvez tenha q mudar aqui
            product_id, unit_price, quantity, discount], delimiter: ','}]
  - name: tap-csv-to-postgres
    inherit_from: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files: [{entity: orders, path: data/order_details.csv, keys: [   #####
            order_id, customer_id, employee_id, order_date, required_date, shipped_date,
            ship_via, freight, ship_name, ship_address, ship_city, ship_region, ship_postal_code,
            ship_country], delimiter: ','}, {entity: orders_details, path: data/order_details.csv,
          keys: [order_id, product_id, unit_price, quantity, discount], delimiter: ','}]
  loaders:

  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
    config:
      database: northwind
      host: localhost
      password: admin
      port: 5432
      user: admin
      default_replication_method: LOG_BASED
      default_target_schema: public

  - name: target-csv-from-postgres
    inherit_from: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      output_path: order_details.csv #./data/postgres/2024-01-01/

  - name: target-csv-from-csv
    inherit_from: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      output_path: order_details.csv

  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
  
  orchestrators:
  - name: airflow
    variant: apache
    pip_url: apache-airflow==2.1.2 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.1.2/constraints-3.9.txt
  
  files:
  - name: files-airflow
    variant: meltano
    pip_url: git+https://github.com/meltano/files-airflow.git
  
  utilities:
  - name: airflow
    variant: apache
    pip_url: git+https://github.com/meltano/airflow-ext.git@main apache-airflow==2.8.1
      --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-no-providers-${MELTANO__PYTHON_VERSION}.txt
jobs:
- name: tap-postgres-csv-to-target-postgres
  tasks:
  - tap-postgres target-csv-from-postgres tap-csv-from-csv target-csv-from-csv
  - tap-csv-to-postgres target-postgres

schedules:
- name: daily-ecommerce-load
  interval: '@daily'
  job: tap-postgres-csv-to-target-postgres